### ISSUE TITLE
copypaste_advanced compatibility with jspreadsheet 11

### ISSUE THREAD

**Issue by randlet** [GBonnaire/jspreadsheet-plugins-and-editors#44]
### Plugin Name with version

Copypaste Advanced  3.3.1

### JSpreadsheet version

v10.x

### Describe the bug

[Jspreadsheet 11 is out now](https://jspreadsheet.com/docs/upgrades) and it included some API changes which broke Advanced Copy Paste v3.3.1 initialization.  In particular `jspreadsheet.events` is no longer available so the code at line 1008 here: https://www.npmjs.com/package/@jspreadsheet/copypaste_advanced?activeTab=code throws an exception.

As a workaround I was able to do `jspreadsheet.events = { paste: jspreadsheet.paste }` and things seem to work ok now.

### Reproduction steps

```bash
1.  Initialize jspreadsheet version 11 with copypaste advanced plugin
2. Observe exception like:
: Cannot read properties of undefined (reading 'paste')
    at Function.<anonymous> (index.js:1008:1)
    at Object.t [as setPlugins] (index.js:122:52)
    at t.<computed> (index.js:123:1)
    at t.<computed> [as spreadsheet] (index.js:408:195)
    at index.js:522:196
```

**Comment by GBonnaire** [comment]
Hi,

Thanks to your signalement. I work on upgrade on my plugins to v11. 

I will update package version limitation

Stay tuned here, i tell you when new version are available

**Comment by randlet** [comment]
Thanks! No rush :)

**Comment by kaushikd74** [comment]
@GBonnaire hey, we are looking for an update to this plugin as well :-)

**Comment by GBonnaire** [comment]
Hey.

thanks i will update soon. sorry for delay
